version: '3.8'            # versão da linguagem Docker Compose

services:                 # Aqui abro para começar a declarar os serviços

  backend:                # Nome do nosso serviço backend
    build: ./backend      # Diz de onde ele vai pegar o Dockerfile
    ports:
      - "3000:3000"       # Aqui estou declarando a porta externa e interna - no caso as duas são 3000
    volumes:
      - ./backend:/app    # Ele sincroniza os arquivos do meu PC com o container
    depends_on:
      - db

  db:                     # Aqui vou colocar o serviço de banco de dados
    image: postgres:15    # Imagem oficial do Postgres na versão 15
    environment:          # Aqui vou definir as váriaveis de ambiente e colocando as configurações do banco de dados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"       # Coloquei a porta padrão do Postgres que é 5432
    volumes:              # Precio deixar claro onde ele vai armazenar as informações
      - pgdata:/var/lib/postgresql/data # Aqui de fato é onde vai ficar armazenada os dados

volumes:
  pgdata:                 # Aqui eu declarei onde vai ser utilizado o volume do banco